version: "3.3"
services:
  
  etcd1: &etcd
    image: etcd
    environment:
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_INITIAL_CLUSTER: node1=http://node1:2380,node2=http://node2:2380,node3=http://node3:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: tutorial
    build:
      context: ./etcd_node1
    container_name: node1
    hostname: node1
    networks:
      network1:
        ipv4_address: 172.16.0.1 
    command: etcd -name node1 -initial-advertise-peer-urls http://node1:2380
    command: etcd -name node1 -advertise-client-urls http://node1:2379  
  etcd2:
    <<: *etcd
    container_name: node2
    hostname: node2
    networks:
      network1:
        ipv4_address: 172.16.0.2 
    command: etcd -name node2 -initial-advertise-peer-urls http://node2:2380
    command: etcd -name node2 -advertise-client-urls http://node2:2379 
  etcd3:
    <<: *etcd
    container_name: node3
    hostname: node3
    networks:
      network1:
        ipv4_address: 172.16.0.3
    command: etcd -name node3 -initial-advertise-peer-urls http://node3:2380
    command: etcd -name node3 -advertise-client-urls http://node3:2379
      
  pp1:
    image: patrpost
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    networks:
      network1:
        ipv4_address: 172.16.0.11 
    restart: on-failure  
    container_name: patrpost1
    hostname: pp1  
    environment:
      PATRONI_NAME: patrpost1
      PATRONI_RESTAPI_CONNECT_ADDRESS: 172.16.0.11:8008
      PATRONI_RESTAPI_LISTEN: 172.16.0.11:8008
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: 172.16.0.11:5432
      PATRONI_POSTGRESQL_LISTEN: 172.16.0.11:5432
    user: postgres
    build:
      context: ./patroni
      dockerfile: Dockerfile
    command: service postgresql restart
    command: patroni /etc/patroni.yml
  pp2:
    image: patrpost
    depends_on:
      - pp1
    networks:
      network1:
        ipv4_address: 172.16.0.12
    container_name: patrpost2
    hostname: pp2  
    environment:
      PATRONI_NAME: patrpost2
      PATRONI_RESTAPI_CONNECT_ADDRESS: 172.16.0.12:8008
      PATRONI_RESTAPI_LISTEN: 172.16.0.12:8008
      PATRONI_POSTGRESQL_LISTEN: 172.16.0.12:5432
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: 172.16.0.12:5432
    user: postgres
    command: service postgresql restart
    command: patroni /etc/patroni.yml
  pp3:
    image: patrpost
    depends_on:
      - pp2
    networks:
      network1:
        ipv4_address: 172.16.0.13
    container_name: patrpost3
    hostname: pp3
    environment:
      PATRONI_NAME: patrpost3
      PATRONI_RESTAPI_CONNECT_ADDRESS: 172.16.0.13:8008
      PATRONI_RESTAPI_LISTEN: 172.16.0.13:8008
      PATRONI_POSTGRESQL_LISTEN: 172.16.0.13:5432
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: 172.16.0.13:5432
    user: postgres
    command: service postgresql restart
    command: patroni /etc/patroni.yml


networks:
  network1:
    external: true
