
version: "3"
services:
  
  etcd:
    image: etcd:latest
    networks:
      - network1
    container_name: node1
    hostname: node1
    ports:
      - "2380:2380"
      - "2379:2379"
      - "8008:8008"
     
    build:
      context: ./etcd_node1
      
  pp:
    image: patrpost:latest
    container_name: node2
    hostname: node2
    depends_on:
      - etcd
    networks:
      - network1
    ports:
      - "5432:5432"
      - "6432:6432"      
    build: 
      context: ./patroni

networks:
  network1:
