ARG  TAG=latest
FROM debian:${TAG} as build

RUN echo 'debconf debconf/frontend select teletype' | debconf-set-selections

RUN apt-get update
RUN apt-get dist-upgrade -y
RUN apt-get install -y --no-install-recommends \
        systemd      \
        systemd-sysv \
        cron         \
        anacron

RUN apt-get clean
RUN rm -rf                        \
    /var/lib/apt/lists/*          \
    /var/log/alternatives.log     \
    /var/log/apt/history.log      \
    /var/log/apt/term.log         \
    /var/log/dpkg.log


RUN systemctl mask --   \
    dev-hugepages.mount \
    sys-fs-fuse-connections.mount

RUN rm -f           \
    /etc/machine-id \
    /var/lib/dbus/machine-id

FROM debian:${TAG}
COPY --from=0 / /

ENV container docker

STOPSIGNAL SIGRTMIN+3

VOLUME [ "/sys/fs/cgroup", "/run", "/run/lock", "/tmp" ]

CMD [ "/sbin/init" ]



FROM systemd_debian

RUN apt-get update && apt-get install curl -y && apt-get install gpg -y && apt-get install curl ca-certificates gnupg && apt-get install vim -y

RUN curl https://www.postgresql.org/media/keys/ACCC4CF8.asc \
| gpg --dearmor \
| tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg > /dev/null 

RUN sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ bullseye-pgdg main" > /etc/apt/sources.list.d/postgresql.list' && \
apt-get update && apt-get upgrade -y && \
apt-get install postgresql-9.6 -y && \
apt-get install python3-pip -y && \   
pip install psycopg2-binary && \
pip install patroni[etcd] && \ 
mkdir -p /data/patroni && \
chown postgres:postgres /data/patroni && \
chmod 777 /data/patroni 

COPY ./patroni.yml ./etc/patroni.yml
COPY ./patroni.service ./etc/systemd/system/patroni.service 

CMD sh

#CMD su postgres service postgresql start

#CMD patroni /etc/patroni.yml


