
FROM debian:latest

RUN apt-get update && apt-get install etcd -y && apt-get install vim -y && apt-get install iputils-ping -y

#COPY ./etcd ./etc/default/etcd     

#RUN service etcd restart

CMD sh




 


